import { CustomRole } from '../types';

// Extracted out of DashboardSettings.tsx into its own tiny module.
// Dashboard.tsx needs this constant unconditionally (role/permission
// fallback logic that runs on every render, not just when the Settings
// tab is open), but DashboardSettings.tsx itself is now lazy-loaded to
// keep it out of the initial post-login bundle. Importing this constant
// FROM DashboardSettings.tsx directly would have pulled the entire
// (large) settings module — and everything it imports — back into the
// eager bundle, defeating that split. This file has no heavy
// dependencies, so importing it eagerly is cheap.
export const DEFAULT_CUSTOM_ROLES: CustomRole[] = [
  {
    id: 'role-seller',
    name: 'Seller',
    permissions: {
      pos: { read: true, write: true, edit: true },
      products: { read: true, write: false, edit: false },
      purchases: { read: false, write: false, edit: false },
      suppliers: { read: false, write: false, edit: false },
      expenses: { read: true, write: true, edit: false },
      reportsSalesExpenses: { read: true, write: false, edit: false },
      reportsProfitCogs: { read: false, write: false, edit: false },
      sync: { read: true, write: true, edit: false },
      settings: { read: false, write: false, edit: false },

      salesList: { read: true, write: false, edit: false },
      salesReturn: { read: false, write: false, edit: false },
      orderPayments: { read: true, write: true, edit: false },
      paymentIn: { read: true, write: true, edit: false },
      paymentOut: { read: false, write: false, edit: false },
      quotation: { read: true, write: true, edit: false },
      stockAdjustment: { read: false, write: false, edit: false },
      stockTransfer: { read: true, write: false, edit: false },
      companySettings: { read: false, write: false, edit: false },
      storageSettings: { read: false, write: false, edit: false },
      emailSettings: { read: false, write: false, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: true, write: false, edit: false },
      storesBranch: { read: false, write: false, edit: false },
      translations: { read: false, write: false, edit: false },
      rolePermissions: { read: false, write: false, edit: false },
      taxes: { read: false, write: false, edit: false },
      currencies: { read: false, write: false, edit: false },
      paymentModes: { read: true, write: false, edit: false },
      units: { read: true, write: false, edit: false },
      customFields: { read: false, write: false, edit: false },
      staffMembers: { read: false, write: false, edit: false },
      customersList: { read: true, write: true, edit: false },
      suppliersList: { read: false, write: false, edit: false },
      saleItemsStats: { read: true, write: false, edit: false },
      totalAmountStats: { read: true, write: false, edit: false },
      totalExpensesStats: { read: false, write: false, edit: false },
      totalPurchasesStats: { read: false, write: false, edit: false },
      totalProfitStats: { read: false, write: false, edit: false },
      salesDueStats: { read: true, write: false, edit: false },
      brands: { read: true, write: false, edit: false },
      productCategories: { read: true, write: false, edit: false },
      productVariations: { read: true, write: false, edit: false },
      productsList: { read: true, write: false, edit: false },
      expenseCategories: { read: true, write: false, edit: false },
      expensesList: { read: true, write: true, edit: false },
      purchaseReturn: { read: false, write: false, edit: false },
      deleteSale: { read: false, write: false, edit: false },
    }
  },
  {
    id: 'role-manager',
    name: 'Manager',
    permissions: {
      pos: { read: true, write: true, edit: true },
      products: { read: true, write: true, edit: true },
      purchases: { read: true, write: true, edit: true },
      suppliers: { read: true, write: true, edit: true },
      expenses: { read: true, write: true, edit: true },
      reportsSalesExpenses: { read: true, write: true, edit: true },
      reportsProfitCogs: { read: true, write: true, edit: true },
      sync: { read: true, write: true, edit: true },
      settings: { read: true, write: true, edit: false },

      salesList: { read: true, write: true, edit: true },
      salesReturn: { read: true, write: true, edit: false },
      orderPayments: { read: true, write: true, edit: true },
      paymentIn: { read: true, write: true, edit: true },
      paymentOut: { read: true, write: true, edit: true },
      quotation: { read: true, write: true, edit: true },
      stockAdjustment: { read: true, write: true, edit: true },
      stockTransfer: { read: true, write: true, edit: true },
      companySettings: { read: true, write: true, edit: false },
      storageSettings: { read: true, write: true, edit: true },
      emailSettings: { read: true, write: true, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: true, write: true, edit: true },
      storesBranch: { read: true, write: false, edit: false },
      translations: { read: true, write: true, edit: false },
      rolePermissions: { read: true, write: false, edit: false },
      taxes: { read: true, write: true, edit: false },
      currencies: { read: true, write: true, edit: false },
      paymentModes: { read: true, write: true, edit: false },
      units: { read: true, write: true, edit: true },
      customFields: { read: true, write: true, edit: false },
      staffMembers: { read: true, write: true, edit: false },
      customersList: { read: true, write: true, edit: true },
      suppliersList: { read: true, write: true, edit: true },
      saleItemsStats: { read: true, write: false, edit: false },
      totalAmountStats: { read: true, write: false, edit: false },
      totalExpensesStats: { read: true, write: false, edit: false },
      totalPurchasesStats: { read: true, write: false, edit: false },
      totalProfitStats: { read: true, write: false, edit: false },
      salesDueStats: { read: true, write: false, edit: false },
      brands: { read: true, write: true, edit: true },
      productCategories: { read: true, write: true, edit: true },
      productVariations: { read: true, write: true, edit: true },
      productsList: { read: true, write: true, edit: true },
      expenseCategories: { read: true, write: true, edit: true },
      expensesList: { read: true, write: true, edit: true },
      purchaseReturn: { read: true, write: true, edit: true },
      deleteSale: { read: true, write: true, edit: true },
    }
  },
  {
    id: 'role-cashier',
    name: 'Cashier',
    permissions: {
      pos: { read: true, write: true, edit: false },
      products: { read: true, write: false, edit: false },
      purchases: { read: false, write: false, edit: false },
      suppliers: { read: false, write: false, edit: false },
      expenses: { read: true, write: true, edit: false },
      reportsSalesExpenses: { read: true, write: false, edit: false },
      reportsProfitCogs: { read: false, write: false, edit: false },
      sync: { read: true, write: false, edit: false },
      settings: { read: false, write: false, edit: false },

      salesList: { read: true, write: false, edit: false },
      salesReturn: { read: false, write: false, edit: false },
      orderPayments: { read: true, write: true, edit: false },
      paymentIn: { read: true, write: true, edit: false },
      paymentOut: { read: false, write: false, edit: false },
      quotation: { read: true, write: false, edit: false },
      stockAdjustment: { read: false, write: false, edit: false },
      stockTransfer: { read: true, write: false, edit: false },
      companySettings: { read: false, write: false, edit: false },
      storageSettings: { read: false, write: false, edit: false },
      emailSettings: { read: false, write: false, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: true, write: false, edit: false },
      storesBranch: { read: false, write: false, edit: false },
      translations: { read: false, write: false, edit: false },
      rolePermissions: { read: false, write: false, edit: false },
      taxes: { read: false, write: false, edit: false },
      currencies: { read: false, write: false, edit: false },
      paymentModes: { read: true, write: false, edit: false },
      units: { read: true, write: false, edit: false },
      customFields: { read: false, write: false, edit: false },
      staffMembers: { read: false, write: false, edit: false },
      customersList: { read: true, write: true, edit: false },
      suppliersList: { read: false, write: false, edit: false },
      saleItemsStats: { read: true, write: false, edit: false },
      totalAmountStats: { read: true, write: false, edit: false },
      totalExpensesStats: { read: false, write: false, edit: false },
      totalPurchasesStats: { read: false, write: false, edit: false },
      totalProfitStats: { read: false, write: false, edit: false },
      salesDueStats: { read: true, write: false, edit: false },
      brands: { read: true, write: false, edit: false },
      productCategories: { read: true, write: false, edit: false },
      productVariations: { read: true, write: false, edit: false },
      productsList: { read: true, write: false, edit: false },
      expenseCategories: { read: true, write: false, edit: false },
      expensesList: { read: true, write: true, edit: false },
      purchaseReturn: { read: false, write: false, edit: false },
      deleteSale: { read: false, write: false, edit: false },
    }
  },
  {
    id: 'role-admin',
    name: 'Admin',
    permissions: {
      pos: { read: true, write: true, edit: true },
      products: { read: true, write: true, edit: true },
      purchases: { read: true, write: true, edit: true },
      suppliers: { read: true, write: true, edit: true },
      expenses: { read: true, write: true, edit: true },
      reportsSalesExpenses: { read: true, write: true, edit: true },
      reportsProfitCogs: { read: true, write: true, edit: true },
      sync: { read: true, write: true, edit: true },
      settings: { read: true, write: true, edit: true },

      salesList: { read: true, write: true, edit: true },
      salesReturn: { read: true, write: true, edit: true },
      orderPayments: { read: true, write: true, edit: true },
      paymentIn: { read: true, write: true, edit: true },
      paymentOut: { read: true, write: true, edit: true },
      quotation: { read: true, write: true, edit: true },
      stockAdjustment: { read: true, write: true, edit: true },
      stockTransfer: { read: true, write: true, edit: true },
      companySettings: { read: true, write: true, edit: true },
      storageSettings: { read: true, write: true, edit: true },
      emailSettings: { read: true, write: true, edit: true },
      updateApp: { read: true, write: true, edit: true },
      cashAndBank: { read: true, write: true, edit: true },
      storesBranch: { read: true, write: true, edit: true },
      translations: { read: true, write: true, edit: true },
      rolePermissions: { read: true, write: true, edit: true },
      taxes: { read: true, write: true, edit: true },
      currencies: { read: true, write: true, edit: true },
      paymentModes: { read: true, write: true, edit: true },
      units: { read: true, write: true, edit: true },
      customFields: { read: true, write: true, edit: true },
      staffMembers: { read: true, write: true, edit: true },
      customersList: { read: true, write: true, edit: true },
      suppliersList: { read: true, write: true, edit: true },
      saleItemsStats: { read: true, write: true, edit: true },
      totalAmountStats: { read: true, write: true, edit: true },
      totalExpensesStats: { read: true, write: true, edit: true },
      totalPurchasesStats: { read: true, write: true, edit: true },
      totalProfitStats: { read: true, write: true, edit: true },
      salesDueStats: { read: true, write: true, edit: true },
      brands: { read: true, write: true, edit: true },
      productCategories: { read: true, write: true, edit: true },
      productVariations: { read: true, write: true, edit: true },
      productsList: { read: true, write: true, edit: true },
      expenseCategories: { read: true, write: true, edit: true },
      expensesList: { read: true, write: true, edit: true },
      purchaseReturn: { read: true, write: true, edit: true },
      deleteSale: { read: true, write: true, edit: true },
    }
  },
  {
    id: 'role-stock-controller',
    name: 'Stock Controller',
    permissions: {
      pos: { read: true, write: false, edit: false },
      products: { read: true, write: true, edit: true },
      purchases: { read: true, write: true, edit: true },
      suppliers: { read: true, write: true, edit: false },
      expenses: { read: false, write: false, edit: false },
      reportsSalesExpenses: { read: true, write: false, edit: false },
      reportsProfitCogs: { read: false, write: false, edit: false },
      sync: { read: true, write: true, edit: false },
      settings: { read: false, write: false, edit: false },

      salesList: { read: true, write: false, edit: false },
      salesReturn: { read: true, write: true, edit: false },
      orderPayments: { read: false, write: false, edit: false },
      paymentIn: { read: false, write: false, edit: false },
      paymentOut: { read: false, write: false, edit: false },
      quotation: { read: true, write: false, edit: false },
      stockAdjustment: { read: true, write: true, edit: true },
      stockTransfer: { read: true, write: true, edit: true },
      companySettings: { read: false, write: false, edit: false },
      storageSettings: { read: true, write: false, edit: false },
      emailSettings: { read: false, write: false, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: false, write: false, edit: false },
      storesBranch: { read: true, write: false, edit: false },
      translations: { read: false, write: false, edit: false },
      rolePermissions: { read: false, write: false, edit: false },
      taxes: { read: false, write: false, edit: false },
      currencies: { read: false, write: false, edit: false },
      paymentModes: { read: false, write: false, edit: false },
      units: { read: true, write: true, edit: false },
      customFields: { read: false, write: false, edit: false },
      staffMembers: { read: false, write: false, edit: false },
      customersList: { read: false, write: false, edit: false },
      suppliersList: { read: true, write: false, edit: false },
      saleItemsStats: { read: true, write: false, edit: false },
      totalAmountStats: { read: false, write: false, edit: false },
      totalExpensesStats: { read: false, write: false, edit: false },
      totalPurchasesStats: { read: true, write: false, edit: false },
      totalProfitStats: { read: false, write: false, edit: false },
      salesDueStats: { read: false, write: false, edit: false },
      brands: { read: true, write: true, edit: true },
      productCategories: { read: true, write: true, edit: true },
      productVariations: { read: true, write: true, edit: true },
      productsList: { read: true, write: true, edit: true },
      expenseCategories: { read: false, write: false, edit: false },
      expensesList: { read: false, write: false, edit: false },
      purchaseReturn: { read: true, write: true, edit: false },
      deleteSale: { read: false, write: false, edit: false },
    }
  },
  {
    id: 'role-delivery-rider',
    name: 'Delivery Rider',
    permissions: {
      pos: { read: false, write: false, edit: false },
      products: { read: true, write: false, edit: false },
      purchases: { read: false, write: false, edit: false },
      suppliers: { read: false, write: false, edit: false },
      expenses: { read: false, write: false, edit: false },
      reportsSalesExpenses: { read: false, write: false, edit: false },
      reportsProfitCogs: { read: false, write: false, edit: false },
      sync: { read: true, write: true, edit: false },
      settings: { read: false, write: false, edit: false },

      salesList: { read: true, write: false, edit: false },
      salesReturn: { read: false, write: false, edit: false },
      orderPayments: { read: true, write: true, edit: false },
      paymentIn: { read: true, write: true, edit: false },
      paymentOut: { read: false, write: false, edit: false },
      quotation: { read: false, write: false, edit: false },
      stockAdjustment: { read: false, write: false, edit: false },
      stockTransfer: { read: true, write: true, edit: false },
      companySettings: { read: false, write: false, edit: false },
      storageSettings: { read: false, write: false, edit: false },
      emailSettings: { read: false, write: false, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: false, write: false, edit: false },
      storesBranch: { read: false, write: false, edit: false },
      translations: { read: false, write: false, edit: false },
      rolePermissions: { read: false, write: false, edit: false },
      taxes: { read: false, write: false, edit: false },
      currencies: { read: false, write: false, edit: false },
      paymentModes: { read: true, write: false, edit: false },
      units: { read: false, write: false, edit: false },
      customFields: { read: false, write: false, edit: false },
      staffMembers: { read: false, write: false, edit: false },
      customersList: { read: true, write: false, edit: false },
      suppliersList: { read: false, write: false, edit: false },
      saleItemsStats: { read: false, write: false, edit: false },
      totalAmountStats: { read: false, write: false, edit: false },
      totalExpensesStats: { read: false, write: false, edit: false },
      totalPurchasesStats: { read: false, write: false, edit: false },
      totalProfitStats: { read: false, write: false, edit: false },
      salesDueStats: { read: false, write: false, edit: false },
      brands: { read: false, write: false, edit: false },
      productCategories: { read: false, write: false, edit: false },
      productVariations: { read: false, write: false, edit: false },
      productsList: { read: true, write: false, edit: false },
      expenseCategories: { read: false, write: false, edit: false },
      expensesList: { read: false, write: false, edit: false },
      purchaseReturn: { read: false, write: false, edit: false },
      deleteSale: { read: false, write: false, edit: false },
    }
  },
  {
    id: 'role-pharmacist',
    name: 'Pharmacist',
    permissions: {
      pos: { read: true, write: true, edit: true },
      products: { read: true, write: true, edit: true },
      purchases: { read: true, write: true, edit: false },
      suppliers: { read: true, write: false, edit: false },
      expenses: { read: true, write: true, edit: false },
      reportsSalesExpenses: { read: true, write: false, edit: false },
      reportsProfitCogs: { read: false, write: false, edit: false },
      sync: { read: true, write: true, edit: false },
      settings: { read: false, write: false, edit: false },

      salesList: { read: true, write: true, edit: false },
      salesReturn: { read: true, write: true, edit: false },
      orderPayments: { read: true, write: true, edit: false },
      paymentIn: { read: true, write: true, edit: false },
      paymentOut: { read: false, write: false, edit: false },
      quotation: { read: true, write: true, edit: false },
      stockAdjustment: { read: true, write: true, edit: false },
      stockTransfer: { read: true, write: false, edit: false },
      companySettings: { read: false, write: false, edit: false },
      storageSettings: { read: false, write: false, edit: false },
      emailSettings: { read: false, write: false, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: false, write: false, edit: false },
      storesBranch: { read: false, write: false, edit: false },
      translations: { read: false, write: false, edit: false },
      rolePermissions: { read: false, write: false, edit: false },
      taxes: { read: false, write: false, edit: false },
      currencies: { read: false, write: false, edit: false },
      paymentModes: { read: true, write: false, edit: false },
      units: { read: true, write: true, edit: false },
      customFields: { read: false, write: false, edit: false },
      staffMembers: { read: false, write: false, edit: false },
      customersList: { read: true, write: true, edit: false },
      suppliersList: { read: true, write: false, edit: false },
      saleItemsStats: { read: true, write: false, edit: false },
      totalAmountStats: { read: true, write: false, edit: false },
      totalExpensesStats: { read: false, write: false, edit: false },
      totalPurchasesStats: { read: true, write: false, edit: false },
      totalProfitStats: { read: false, write: false, edit: false },
      salesDueStats: { read: true, write: false, edit: false },
      brands: { read: true, write: true, edit: false },
      productCategories: { read: true, write: true, edit: false },
      productVariations: { read: true, write: true, edit: true },
      productsList: { read: true, write: true, edit: true },
      expenseCategories: { read: true, write: false, edit: false },
      expensesList: { read: true, write: true, edit: false },
      purchaseReturn: { read: true, write: true, edit: false },
      deleteSale: { read: false, write: false, edit: false },
    }
  },
  {
    id: 'role-accountant',
    name: 'Accountant',
    permissions: {
      pos: { read: true, write: false, edit: false },
      products: { read: true, write: false, edit: false },
      purchases: { read: true, write: true, edit: true },
      suppliers: { read: true, write: true, edit: false },
      expenses: { read: true, write: true, edit: true },
      reportsSalesExpenses: { read: true, write: true, edit: false },
      reportsProfitCogs: { read: true, write: true, edit: false },
      sync: { read: true, write: true, edit: false },
      settings: { read: false, write: false, edit: false },

      salesList: { read: true, write: false, edit: false },
      salesReturn: { read: true, write: false, edit: false },
      orderPayments: { read: true, write: true, edit: true },
      paymentIn: { read: true, write: true, edit: true },
      paymentOut: { read: true, write: true, edit: true },
      quotation: { read: true, write: false, edit: false },
      stockAdjustment: { read: true, write: false, edit: false },
      stockTransfer: { read: true, write: false, edit: false },
      companySettings: { read: false, write: false, edit: false },
      storageSettings: { read: false, write: false, edit: false },
      emailSettings: { read: false, write: false, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: true, write: true, edit: true },
      storesBranch: { read: true, write: false, edit: false },
      translations: { read: false, write: false, edit: false },
      rolePermissions: { read: false, write: false, edit: false },
      taxes: { read: true, write: true, edit: false },
      currencies: { read: true, write: false, edit: false },
      paymentModes: { read: true, write: false, edit: false },
      units: { read: true, write: false, edit: false },
      customFields: { read: false, write: false, edit: false },
      staffMembers: { read: false, write: false, edit: false },
      customersList: { read: true, write: false, edit: false },
      suppliersList: { read: true, write: true, edit: false },
      saleItemsStats: { read: true, write: false, edit: false },
      totalAmountStats: { read: true, write: false, edit: false },
      totalExpensesStats: { read: true, write: false, edit: false },
      totalPurchasesStats: { read: true, write: false, edit: false },
      totalProfitStats: { read: true, write: false, edit: false },
      salesDueStats: { read: true, write: false, edit: false },
      brands: { read: true, write: false, edit: false },
      productCategories: { read: true, write: false, edit: false },
      productVariations: { read: true, write: false, edit: false },
      productsList: { read: true, write: false, edit: false },
      expenseCategories: { read: true, write: true, edit: false },
      expensesList: { read: true, write: true, edit: true },
      purchaseReturn: { read: true, write: true, edit: false },
      deleteSale: { read: false, write: false, edit: false },
    }
  },
  {
    id: 'role-supervisor',
    name: 'Supervisor',
    permissions: {
      pos: { read: true, write: true, edit: true },
      products: { read: true, write: true, edit: false },
      purchases: { read: true, write: false, edit: false },
      suppliers: { read: true, write: false, edit: false },
      expenses: { read: true, write: true, edit: false },
      reportsSalesExpenses: { read: true, write: false, edit: false },
      reportsProfitCogs: { read: true, write: false, edit: false },
      sync: { read: true, write: true, edit: false },
      settings: { read: false, write: false, edit: false },

      salesList: { read: true, write: true, edit: false },
      salesReturn: { read: true, write: true, edit: false },
      orderPayments: { read: true, write: true, edit: false },
      paymentIn: { read: true, write: true, edit: false },
      paymentOut: { read: false, write: false, edit: false },
      quotation: { read: true, write: true, edit: false },
      stockAdjustment: { read: true, write: true, edit: false },
      stockTransfer: { read: true, write: false, edit: false },
      companySettings: { read: false, write: false, edit: false },
      storageSettings: { read: false, write: false, edit: false },
      emailSettings: { read: false, write: false, edit: false },
      updateApp: { read: false, write: false, edit: false },
      cashAndBank: { read: true, write: false, edit: false },
      storesBranch: { read: true, write: false, edit: false },
      translations: { read: false, write: false, edit: false },
      rolePermissions: { read: false, write: false, edit: false },
      taxes: { read: false, write: false, edit: false },
      currencies: { read: false, write: false, edit: false },
      paymentModes: { read: true, write: false, edit: false },
      units: { read: true, write: false, edit: false },
      customFields: { read: false, write: false, edit: false },
      staffMembers: { read: true, write: false, edit: false },
      customersList: { read: true, write: true, edit: false },
      suppliersList: { read: true, write: false, edit: false },
      saleItemsStats: { read: true, write: false, edit: false },
      totalAmountStats: { read: true, write: false, edit: false },
      totalExpensesStats: { read: true, write: false, edit: false },
      totalPurchasesStats: { read: false, write: false, edit: false },
      totalProfitStats: { read: true, write: false, edit: false },
      salesDueStats: { read: true, write: false, edit: false },
      brands: { read: true, write: false, edit: false },
      productCategories: { read: true, write: false, edit: false },
      productVariations: { read: true, write: false, edit: false },
      productsList: { read: true, write: false, edit: false },
      expenseCategories: { read: true, write: false, edit: false },
      expensesList: { read: true, write: true, edit: false },
      purchaseReturn: { read: true, write: false, edit: false },
      deleteSale: { read: false, write: false, edit: false },
    }
  }
];
