/**
 * add-ar-fr.mjs
 * ---------------------------------------------------------------------------
 * Inaongeza tafsiri za Kiarabu (AR) na Kifaransa (FR) zilizokosekana
 * ndani ya src/LanguageContext.tsx.
 *
 * Salama:
 *   - Backup inatengenezwa kabla ya kubadilisha chochote.
 *   - Funguo zilizokwishakuwepo zinarukwa (hakuna kurudufu).
 *   - Ikishindwa, faili ya asili haiguswi.
 *
 * Matumizi:
 *   node scripts/add-ar-fr.mjs
 */

import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs';

const FILE = 'src/LanguageContext.tsx';

const AR = {
  "1 package contains": "الحزمة الواحدة تحتوي على",
  "a4 office print preview mode": "معاينة الطباعة بحجم A4",
  "account history & transactions": "سجل الحساب والمعاملات",
  "account identifier": "رقم الهاتف أو البريد الإلكتروني",
  "accountant": "محاسب",
  "accounts transfer guidelines": "إرشادات تحويل الأموال",
  "active cashier till payments": "طرق دفع الكاشير النشطة",
  "active configurations layout": "تخطيط الإعدادات النشطة",
  "active delivery settings (payment methods)": "إعدادات التوصيل النشطة (طرق الدفع)",
  "active selling channels": "قنوات البيع النشطة",
  "active staff": "الموظفون النشطون",
  "active stock": "المنتجات المتوفرة",
  "ad exchange ssp": "منصة عرض الإعلانات",
  "ad placement": "موضع الإعلان",
  "ad placements": "مواضع الإعلانات",
  "add a new term or policy clause": "إضافة شرط أو بند جديد",
  "add category": "إضافة فئة",
  "add custom method": "إضافة طريقة مخصصة",
  "add delivery payment method": "إضافة طريقة دفع للتوصيل",
  "add new product": "إضافة منتج جديد",
  "add payment method": "إضافة طريقة دفع",
  "add role": "إضافة دور",
  "add store location": "إضافة موقع مخزن",
  "add unit": "إضافة وحدة",
  "add where money can be sent": "إضافة وجهة لإرسال الأموال",
  "add your first product": "أضف أول منتج لك",
  "admin": "مدير النظام",
  "ads by jb": "إعلانات JB",
  "affiliate": "شريك تسويق",
  "aggregate outflow": "إجمالي المصروفات",
  "alert": "تنبيه",
  "all": "الكل",
  "all items are stocked above target safety levels": "جميع المنتجات فوق مستوى الأمان",
  "all systems running normally": "جميع الأنظمة تعمل بشكل طبيعي",
  "allowance": "بدل",
  "allowances": "البدلات",
  "analytics": "التحليلات",
  "audit ledger": "سجل التقارير",
  "authorized measurement units (uom)": "وحدات القياس المعتمدة",
  "auto if empty": "تلقائي إذا ترك فارغًا",
  "auto-created from your company name.": "يُنشأ تلقائيًا من اسم شركتك.",
  "auto-generated-key": "مفتاح تلقائي",
  "awaiting layout selection and customer assignment": "بانتظار اختيار التخطيط وتحديد العميل",
  "barcode controls & stock": "الباركود والمخزون",
  "barcode label layout option": "خيار تخطيط ملصق الباركود",
  "base unit": "الوحدة الأساسية",
  "best sellers": "الأكثر مبيعًا",
  "billing & delivery address": "عنوان الفاتورة والتوصيل",
  "branch yield": "إيرادات الفرع",
  "brand directories": "أدلة العلامات التجارية",
  "bulk template": "قالب جماعي",
  "bulk upload": "رفع جماعي",
  "business address": "عنوان النشاط",
  "business email": "البريد الإلكتروني للنشاط",
  "business industry niche": "نوع النشاط",
  "business industry niche / type": "نوع النشاط",
  "business intelligence": "تقارير الأعمال",
  "business phone": "هاتف النشاط",
  "business profile": "ملف النشاط",
  "business settings": "إعدادات النشاط",
  "business setup": "إعداد النشاط",
  "buying": "الشراء",
  "call local agent": "اتصل بالوكيل المحلي",
  "canvas processing": "جارٍ معالجة الصورة",
  "cartons per master box": "الكراتين في الصندوق الكبير",
  "cash & bank": "النقد والبنك",
  "cash bank matrix": "جدول النقد والبنك",
  "cash-bank-matrix screen": "شاشة النقد والبنك",
  "cashier override": "تجاوز الكاشير",
  "categories": "الفئات",
  "category directories": "أدلة الفئات",
  "central vaults & bank accounts": "الخزائن والحسابات البنكية",
  "channel rules & costs": "قواعد وتكاليف القنوات",
  "choose package": "اختر الباقة",
  "choose payment mode for detailed date-based metrics": "اختر طريقة الدفع لعرض التفاصيل حسب التاريخ",
  "choose the product type, starting level, and how many units each level contains.": "اختر نوع المنتج والمستوى الأول وعدد الوحدات في كل مستوى.",
  "city / office location": "المدينة",
  "click to remove payment channel": "اضغط لحذف قناة الدفع",
  "cloud network connected": "متصل بالسحابة",
  "cloud synchronized ledger node": "سجل متزامن مع السحابة",
  "code & link": "الرمز والرابط",
  "collapse sidebar": "طي القائمة الجانبية",
  "collect due balance installment": "تحصيل قسط من الرصيد المستحق",
  "commercial profit & loss account": "تقرير الأرباح والخسائر",
  "commit ledger": "حفظ المصروف",
  "communicating with payment server": "جارٍ الاتصال بخادم الدفع",
  "company / business name": "اسم الشركة أو النشاط",
  "company address": "عنوان الشركة",
  "company code": "رمز الشركة",
  "company legal name": "الاسم القانوني للشركة",
  "company level settings": "إعدادات الشركة",
  "company tin (taxpayer identification number)": "الرقم الضريبي للشركة",
  "company vat registration number": "رقم تسجيل ضريبة القيمة المضافة",
  "compile report": "إنشاء تقرير",
  "configure core business metadata, localized compliance tin/vat numbers, legal currency markers, and system color mode preferences.": "اضبط بيانات النشاط الأساسية والأرقام الضريبية ورمز العملة ووضع ألوان النظام.",
  "configure corporate accounts & bank keys in settings": "اضبط حسابات الشركة والمفاتيح البنكية في الإعدادات",
  "configure new selling price": "تحديد سعر بيع جديد",
  "confirm & initialize payment": "تأكيد وبدء الدفع",
  "conflict overrides action log": "سجل تجاوزات التعارض",
  "consolidated margin curve": "رسم المبيعات والأرباح",
  "contact for deployment": "تواصل معنا للتفعيل",
  "contact helpline / phone no": "رقم الدعم",
  "continue": "متابعة",
  "copied": "تم النسخ",
  "copy": "نسخ",
  "corporate headquarters address": "عنوان المقر الرئيسي",
  "cost of goods sold": "تكلفة البضاعة",
  "cost of purchase": "تكلفة الشراء",
  "create": "إنشاء",
  "custom interval": "اختر التواريخ",
  "custom roles & permissions": "الأدوار والصلاحيات المخصصة",
  "customer identity (required for store credit)": "بيانات العميل (مطلوبة للبيع الآجل)",
  "customer totals and credit": "إجماليات العميل والرصيد الآجل",
  "customers screen": "شاشة العملاء",
  "daily": "يومي",
  "daily sales volume timeline": "حجم المبيعات اليومي",
  "dashboard ad code published.": "تم نشر كود إعلان لوحة التحكم.",
  "dashboard ad deleted and turned off.": "تم حذف إعلان لوحة التحكم وإيقافه.",
  "dashboard ad placement": "موضع إعلان لوحة التحكم",
  "dashboard ads": "إعلانات لوحة التحكم",
  "date aggregated timeline transactions": "المعاملات مجمعة حسب التاريخ",
  "days remaining": "الأيام المتبقية",
  "de-register store storage bin": "إلغاء تسجيل موقع التخزين",
  "default portion qty": "الكمية الافتراضية للجزء",
  "deferred credit": "الدفع الآجل",
  "define packet, dose and tab selling": "حدد بيع العبوة والجرعة والحبة",
  "delete item": "حذف العنصر",
  "delete role": "حذف الدور",
  "deliveries screen": "شاشة التوصيل",
  "delivery menu": "قائمة التوصيل",
  "delivery payment methods": "طرق دفع التوصيل",
  "delivery rider": "مندوب التوصيل",
  "department": "القسم",
  "descriptor & visual assets": "الوصف والصور",
  "device is offline": "الجهاز غير متصل",
  "device is online": "الجهاز متصل",
  "direct phone line": "خط هاتف مباشر",
  "disabled": "معطل",
  "discard": "إلغاء",
  "dose / middle price": "سعر الجرعة",
  "download csv": "تنزيل CSV",
  "download pdf": "تنزيل PDF",
  "download spreadsheet template": "تنزيل قالب الجدول",
  "download template": "تنزيل القالب",
  "dual channel": "التجزئة والجملة",
  "dues owed": "المستحقات",
  "edit item": "تعديل العنصر",
  "edit login": "تعديل بيانات الدخول",
  "edit role": "تعديل الدور",
  "email address": "البريد الإلكتروني",
  "enabled": "مفعّل",
  "english": "الإنجليزية",
  "enter brand name": "أدخل اسم العلامة التجارية",
  "enter business brand name": "أدخل اسم العلامة التجارية للنشاط",
  "enter category": "أدخل الفئة",
  "enter company legal registry name": "أدخل الاسم القانوني المسجل للشركة",
  "enter company legal registry name...": "أدخل الاسم القانوني المسجل للشركة...",
  "enter product name": "أدخل اسم المنتج",
  "enter supervisor override code": "أدخل رمز تجاوز المشرف",
  "expenses management": "إدارة المصروفات",
  "expenses screen": "شاشة المصروفات",
  "export csv": "تصدير CSV",
  "export pdf": "تصدير PDF",
  "fast movers": "المنتجات سريعة البيع",
  "fifo, average, and batch price control.": "التحكم في الأسعار بطريقة الوارد أولًا والمتوسط والدفعات.",
  "filter by customer, phone, or ticket ref": "تصفية حسب العميل أو الهاتف أو رقم الفاتورة",
  "filter invoice ledger list by customized date intervals": "تصفية قائمة الفواتير حسب فترات تاريخية مخصصة",
  "filter report": "تصفية التقرير",
  "fits images & separates background instantly": "يضبط الصور ويفصل الخلفية فورًا",
  "flyer": "منشور دعائي",
  "forecasting": "التوقعات",
  "forecasting screen": "شاشة التوقعات",
  "generated based on company name for subdomain routing": "يُنشأ من اسم الشركة لتوجيه النطاق الفرعي",
  "generated company username/key": "اسم المستخدم أو المفتاح المُنشأ للشركة",
  "gross income": "إجمالي الدخل",
  "gross revenue": "إجمالي المبيعات",
  "hali ya mauzo na manunuzi": "حالة المبيعات والمشتريات",
  "helpline displayed on layouts": "رقم الدعم الظاهر على المستندات",
  "image": "صورة",
  "import": "استيراد",
  "inspect client receipt details": "عرض تفاصيل فاتورة العميل",
  "intelligence & auditing": "تقارير الأعمال",
  "inventory sales distribution": "توزيع مبيعات المخزون",
  "inventory screen": "شاشة المخزون",
  "invoice & branding customization": "تخصيص الفاتورة والهوية",
  "invoice footer tagline / memo": "ملاحظة أسفل الفاتورة",
  "items sold": "المنتجات المباعة",
  "label directories": "أدلة الملصقات",
  "last sync": "آخر مزامنة",
  "last30Days": "آخر 30 يومًا",
  "last7Days": "آخر 7 أيام",
  "leave blank to auto-create sku": "اتركه فارغًا لإنشاء رمز المنتج تلقائيًا",
  "ledger actions": "إجراءات السجل",
  "ledger analytics": "تحليلات السجل",
  "legal payment currency symbol": "رمز العملة الرسمية",
  "legal street, plot no, city, country": "الشارع، رقم القطعة، المدينة، الدولة",
  "liquidity & consolidated cash flow": "السيولة والتدفق النقدي",
  "live manager override station": "محطة تجاوز المدير المباشرة",
  "loading...": "جارٍ التحميل...",
  "local mode (offline)": "الوضع المحلي (غير متصل)",
  "locked": "مقفل",
  "low stock alert level": "مستوى تنبيه نقص المخزون",
  "low stock alerts": "تنبيهات نقص المخزون",
  "lowest unit": "أصغر وحدة",
  "lucy ai": "لوسي الذكية",
  "lucy assistant": "المساعدة لوسي",
  "manage": "إدارة",
  "manage active subscriptions and premium account plans easily to expand store limits.": "أدر الاشتراكات النشطة والباقات المميزة بسهولة لتوسيع حدود المتجر.",
  "manager": "مدير",
  "margin gain per unit": "هامش الربح لكل وحدة",
  "materials": "المواد",
  "meetings": "الاجتماعات",
  "min wholesale qty": "أقل كمية للجملة",
  "month": "شهر",
  "monthly": "شهري",
  "multi-channel split breakdown": "تفصيل القنوات المتعددة",
  "my jasper suite": "جاسبر الخاص بي",
  "net gross profit": "الربح",
  "net outcome in selected range": "صافي النتيجة في الفترة المحددة",
  "new buying cost (per unit)": "تكلفة الشراء الجديدة (للوحدة)",
  "new category": "فئة جديدة",
  "new commercial sales document wizard": "معالج إنشاء مستند بيع جديد",
  "new product": "منتج جديد",
  "new unit": "وحدة جديدة",
  "no changes to selling price": "لا تغيير في سعر البيع",
  "no delivery payment methods. pos default will be applied": "لا توجد طرق دفع للتوصيل. سيتم استخدام الافتراضي",
  "no image": "لا توجد صورة",
  "no logistics delivery transactions logged yet": "لا توجد عمليات توصيل مسجلة بعد",
  "no operating expenses recorded within selected range": "لا توجد مصروفات مسجلة في الفترة المحددة",
  "no products yet": "لا توجد منتجات بعد",
  "no sales transactions found in selected period": "لا توجد مبيعات في الفترة المحددة",
  "no tenant suite available": "لا توجد مساحة عمل متاحة",
  "no transactions matched research parameters": "لا توجد معاملات مطابقة للبحث",
  "non-pharmaceutical": "غير دوائي",
  "none": "لا شيء",
  "notifications & auto reports": "الإشعارات والتقارير التلقائية",
  "off": "إيقاف",
  "on": "تشغيل",
  "onboarding": "التسجيل الأولي",
  "online now": "متصل الآن",
  "open": "فتح",
  "open workspace menu": "فتح قائمة مساحة العمل",
  "operating expenses burden": "مصروفات التشغيل",
  "operating expenses logs receipt": "إيصال سجل المصروفات",
  "operational integrity intact": "سلامة التشغيل مؤكدة",
  "order": "طلب",
  "orders": "الطلبات",
  "orders / tx": "الطلبات والمعاملات",
  "organic subscribers": "المشتركون الطبيعيون",
  "outbound stock pulling logic": "آلية سحب المخزون الصادر",
  "outstanding sales invoices marked as credit tabs": "فواتير البيع الآجل غير المسددة",
  "overall report": "التقرير العام",
  "overview": "نظرة عامة",
  "overview screen": "شاشة النظرة العامة",
  "owner full name": "الاسم الكامل للمالك",
  "owner pin password": "كلمة المرور",
  "package": "الباقة",
  "package name": "اسم الباقة",
  "packages": "الباقات",
  "packet, dose, half dose and tab pricing": "تسعير العبوة والجرعة ونصف الجرعة والحبة",
  "partner": "شريك",
  "past 1 year": "آخر سنة",
  "past 3 months": "آخر 3 أشهر",
  "past 7 days": "آخر 7 أيام",
  "past30Days": "آخر 30 يومًا",
  "payment methods": "طرق الدفع",
  "payouts": "المدفوعات",
  "pending sync": "بانتظار المزامنة",
  "permanent": "دائم",
  "permissions": "الصلاحيات",
  "pharmaceutical": "دوائي",
  "pharmacist": "صيدلي",
  "pharmacy": "صيدلية",
  "pharmacy unit hierarchy": "تسلسل وحدات الصيدلية",
  "phone number": "رقم الهاتف",
  "phone number (optional)": "رقم الهاتف (اختياري)",
  "phone with country code": "الهاتف مع رمز الدولة",
  "png signature (500x500 pix)": "توقيع PNG (500×500 بكسل)",
  "point of sale (pos)": "نقطة البيع",
  "pos screen": "شاشة نقطة البيع",
  "preferences": "التفضيلات",
  "preview": "معاينة",
  "print report": "طباعة التقرير",
  "print standard a4 pdf document": "طباعة مستند PDF بحجم A4",
  "procurement": "المشتريات",
  "product brand": "العلامة التجارية للمنتج",
  "product catalogue": "كتالوج المنتجات",
  "product image": "صورة المنتج",
  "product markup": "هامش ربح المنتج",
  "product name / title": "اسم المنتج",
  "product profitability": "ربحية المنتج",
  "product search & picker tool": "أداة البحث واختيار المنتجات",
  "product type": "نوع المنتج",
  "products below security thresholds": "منتجات تحت حد الأمان",
  "products management": "إدارة المنتجات",
  "products screen": "شاشة المنتجات",
  "profile photo (500x500 pix)": "صورة الملف الشخصي (500×500 بكسل)",
  "profile settings": "إعدادات الملف الشخصي",
  "profit": "الربح",
  "profit & cogs reports": "تقارير الربح وتكلفة البضاعة",
  "profit margin": "هامش الربح",
  "promotional materials": "المواد الترويجية",
  "provide audited verification slip": "قدّم إيصال التحقق المدقق",
  "purchase trend": "اتجاه المشتريات",
  "purchases list": "قائمة المشتريات",
  "purchases management": "إدارة المشتريات",
  "quantity added": "الكمية المضافة",
  "quick actions": "إجراءات سريعة",
  "quick sale": "بيع سريع",
  "quick sale portions": "أجزاء البيع السريع",
  "quotations & proforma invoices": "عروض الأسعار والفواتير المبدئية",
  "read": "قراءة",
  "ready for direct printing or local downloads": "جاهز للطباعة المباشرة أو التنزيل",
  "real-time audit log with operational action menus": "سجل تدقيق فوري مع قوائم الإجراءات",
  "received payments & channel ledger": "المدفوعات المستلمة وسجل القنوات",
  "recent sales": "المبيعات الأخيرة",
  "region of operations": "الدولة أو المنطقة",
  "register new product": "تسجيل منتج جديد",
  "register new staff profile": "تسجيل ملف موظف جديد",
  "register staff": "تسجيل موظف",
  "registered": "مسجل",
  "registered categories": "الفئات المسجلة",
  "registered staff": "الموظفون المسجلون",
  "registered staff accounts": "حسابات الموظفين المسجلة",
  "registered units": "الوحدات المسجلة",
  "registered warehouses & store stock locations": "المستودعات ومواقع التخزين المسجلة",
  "remaining customer dockets debt pending settlement": "ديون العملاء المتبقية بانتظار السداد",
  "removes image background.": "يزيل خلفية الصورة.",
  "replenish stock": "تجديد المخزون",
  "reporting terminal": "التقارير",
  "reports screen": "شاشة التقارير",
  "retail & wholesale": "التجزئة والجملة",
  "retail package selling": "بيع عبوات التجزئة",
  "retail price": "سعر التجزئة",
  "retail scan barcode (acts as sku item code)": "باركود التجزئة (يُستخدم كرمز المنتج)",
  "retry": "إعادة المحاولة",
  "role": "الدور",
  "role name": "اسم الدور",
  "roles": "الأدوار",
  "salary": "الراتب",
  "salary type": "نوع الراتب",
  "sales & expenses reports": "تقارير المبيعات والمصروفات",
  "sales & purchase status": "حالة المبيعات والمشتريات",
  "sales forecasting": "توقعات المبيعات",
  "sales list": "قائمة المبيعات",
  "sales trend": "اتجاه المبيعات",
  "sales velocity": "سرعة المبيعات",
  "save / edit ad code": "حفظ أو تعديل كود الإعلان",
  "save / edit bottom ad": "حفظ أو تعديل الإعلان السفلي",
  "save ad code": "حفظ كود الإعلان",
  "save bottom ad": "حفظ الإعلان السفلي",
  "save changes": "حفظ التغييرات",
  "save login": "حفظ بيانات الدخول",
  "save registration": "حفظ التسجيل",
  "save settings": "حفظ الإعدادات",
  "saved": "تم الحفظ",
  "saving": "جارٍ الحفظ",
  "saving...": "جارٍ الحفظ...",
  "scan barcode / qr ean code with reader": "امسح الباركود أو رمز QR بالقارئ",
  "search and select items to print barcodes for": "ابحث واختر المنتجات لطباعة الباركود",
  "search code, barcode or title": "ابحث بالرمز أو الباركود أو الاسم",
  "search customer, staff code, item": "ابحث عن عميل أو رمز موظف أو منتج",
  "search products...": "ابحث عن المنتجات...",
  "search receipt id, client customer name": "ابحث برقم الفاتورة أو اسم العميل",
  "search transactions": "بحث في المعاملات",
  "search workspace": "بحث في مساحة العمل",
  "search workspace...": "بحث في مساحة العمل...",
  "select active payment rail": "اختر قناة الدفع النشطة",
  "select an audited branch segment to inspect": "اختر فرعًا مدققًا للفحص",
  "select and add catalog items above": "اختر وأضف منتجات من الكتالوج أعلاه",
  "select category": "اختر الفئة",
  "select core source account": "اختر الحساب المصدر",
  "select language": "اختر اللغة",
  "select language / badili lugha": "اختر اللغة",
  "select language / velg pris / badili lugha": "اختر اللغة",
  "select target wallet or bank": "اختر المحفظة أو البنك المستهدف",
  "selected payment mode details": "تفاصيل طريقة الدفع المختارة",
  "sell / count unit": "وحدة البيع أو العد",
  "sell mode": "وضع البيع",
  "sell retail": "بيع تجزئة",
  "sell wholesale": "بيع جملة",
  "seller": "بائع",
  "set as transfer source & open panel": "تعيين كمصدر تحويل وفتح اللوحة",
  "set low-stock alert.": "اضبط تنبيه نقص المخزون.",
  "settings access": "الوصول إلى الإعدادات",
  "settings screen": "شاشة الإعدادات",
  "settle outstanding payment-in": "تسوية المبالغ المستحقة",
  "shop": "المتجر",
  "show product pictures in pos": "إظهار صور المنتجات في نقطة البيع",
  "shows name & barcode text (no price)": "يعرض الاسم والباركود بدون سعر",
  "shows name, price & barcode": "يعرض الاسم والسعر والباركود",
  "shows only the scan barcode bars": "يعرض أعمدة الباركود فقط",
  "sign out failed, please try again": "فشل تسجيل الخروج، حاول مرة أخرى",
  "simulated push dispatched": "تم إرسال إشعار تجريبي",
  "slow movers": "المنتجات بطيئة البيع",
  "smart batch costing": "تكلفة الدفعات الذكية",
  "smart pos & business management": "نقطة بيع ذكية وإدارة أعمال",
  "staff & hr": "الموظفون والموارد البشرية",
  "staff control center": "مركز إدارة الموظفين",
  "staff member": "موظف",
  "staff members": "الموظفون",
  "staff onboarding": "تسجيل الموظفين",
  "staff payroll, sessions and performance": "رواتب الموظفين والجلسات والأداء",
  "staff type": "نوع الموظف",
  "standard staff": "موظف عادي",
  "starting level": "المستوى الأول",
  "statement line items": "تفاصيل التقرير",
  "sticky bottom ad banner": "بانر إعلاني سفلي ثابت",
  "sticky bottom ad deleted and turned off.": "تم حذف الإعلان السفلي الثابت وإيقافه.",
  "sticky bottom ad published.": "تم نشر الإعلان السفلي الثابت.",
  "stock alerts": "تنبيهات المخزون",
  "stock controller": "مسؤول المخزون",
  "stock replenishment": "تجديد المخزون",
  "stock replenishment & prices": "تجديد المخزون والأسعار",
  "stock valuations & warehouse split": "تقييم المخزون وتوزيع المستودعات",
  "store": "المتجر",
  "store location": "موقع المخزن",
  "store locations": "مواقع المخازن",
  "strips per box": "الشرائط في العلبة",
  "sub affiliate subscribers": "مشتركو الشركاء الفرعيين",
  "sub affiliates": "الشركاء الفرعيون",
  "submit payment-in reference": "إرسال مرجع الدفعة",
  "subscribe": "اشترك",
  "subscription": "الاشتراك",
  "sum outcome inside date range": "إجمالي النتيجة في الفترة",
  "supervisor": "مشرف",
  "supplier": "المورد",
  "suppliers management": "إدارة الموردين",
  "suppliers screen": "شاشة الموردين",
  "supported formats: jpg, png, webp. maximum file size: 2mb": "الصيغ المدعومة: JPG، PNG، WEBP. الحد الأقصى: 2 ميجابايت",
  "swahili": "السواحيلية",
  "switch to dark mode": "التبديل إلى الوضع الداكن",
  "switch to day mode": "التبديل إلى الوضع النهاري",
  "switch to light mode": "التبديل إلى الوضع الفاتح",
  "sync now": "مزامنة الآن",
  "system & branch configurations": "إعدادات النظام والفروع",
  "system module / functionality": "وحدة النظام أو الوظيفة",
  "system settings": "إعدادات النظام",
  "system subscription options": "خيارات اشتراك النظام",
  "tagline": "الشعار النصي",
  "talk to lucy": "تحدث مع لوسي",
  "tasks": "المهام",
  "tax identification number (tin)": "الرقم الضريبي",
  "temporary": "مؤقت",
  "temporary staff": "موظف مؤقت",
  "tenant": "المستأجر",
  "tenants": "المستأجرون",
  "today's sale": "مبيعات اليوم",
  "today's sales": "مبيعات اليوم",
  "todays sales": "مبيعات اليوم",
  "top products": "أفضل المنتجات",
  "total allowances": "إجمالي البدلات",
  "total payment in (inflows)": "إجمالي المقبوضات",
  "total payment out (outflows)": "إجمالي المدفوعات",
  "total payment-ins collected": "إجمالي المقبوضات المحصلة",
  "total payroll": "إجمالي الرواتب",
  "total spending": "إجمالي الإنفاق",
  "total staff": "إجمالي الموظفين",
  "total staff cost": "إجمالي تكلفة الموظفين",
  "tracked skus": "المنتجات المتتبعة",
  "trial expired": "انتهت الفترة التجريبية",
  "type product name or barcode to add": "اكتب اسم المنتج أو الباركود للإضافة",
  "unified branch accounts & reports": "حسابات وتقارير الفروع الموحدة",
  "unified stock registry desk": "سجل المخزون الموحد",
  "units": "الوحدات",
  "units moved": "المنتجات المباعة",
  "update customer details or items": "تحديث بيانات العميل أو المنتجات",
  "update settings": "تحديث الإعدادات",
  "upload product image": "رفع صورة المنتج",
  "upload spreadsheet": "رفع جدول بيانات",
  "used to sign in & receive otp resets": "يُستخدم لتسجيل الدخول واستلام رموز التحقق",
  "username": "اسم المستخدم",
  "vat number": "رقم ضريبة القيمة المضافة",
  "vat-yyyyyy-y (if applicable)": "VAT-YYYYYY-Y (إن وجد)",
  "verification email address": "البريد الإلكتروني للتحقق",
  "video": "فيديو",
  "view details": "عرض التفاصيل",
  "view or print thermal slip": "عرض أو طباعة الإيصال الحراري",
  "view product": "عرض المنتج",
  "void / clear entire basket": "إلغاء أو مسح السلة بالكامل",
  "void transaction indices permanently": "إلغاء المعاملات نهائيًا",
  "waiter": "نادل",
  "week": "أسبوع",
  "weekly": "أسبوعي",
  "whatsapp / mobile number": "واتساب أو رقم الجوال",
  "whole package sale value": "قيمة بيع العبوة الكاملة",
  "why are you moving this money": "لماذا تنقل هذه الأموال",
  "write": "كتابة",
  "year": "سنة",
  "your whatsapp / mobile number": "واتساب أو رقم جوالك",
};

const FR = {
  "1 package contains": "1 paquet contient",
  "a4 office print preview mode": "Aperçu d'impression A4",
  "account history & transactions": "Historique du compte et transactions",
  "account identifier": "Numéro de téléphone ou e-mail",
  "accountant": "Comptable",
  "accounts transfer guidelines": "Guide des transferts d'argent",
  "active cashier till payments": "Modes de paiement caisse actifs",
  "active configurations layout": "Disposition des configurations actives",
  "active delivery settings (payment methods)": "Paramètres de livraison actifs (modes de paiement)",
  "active selling channels": "Canaux de vente actifs",
  "active staff": "Personnel actif",
  "active stock": "Produits en stock",
  "ad exchange ssp": "Régie publicitaire",
  "ad placement": "Emplacement publicitaire",
  "ad placements": "Emplacements publicitaires",
  "add a new term or policy clause": "Ajouter une clause ou une condition",
  "add category": "Ajouter une catégorie",
  "add custom method": "Ajouter une méthode personnalisée",
  "add delivery payment method": "Ajouter un mode de paiement livraison",
  "add new product": "Ajouter un nouveau produit",
  "add payment method": "Ajouter un mode de paiement",
  "add role": "Ajouter un rôle",
  "add store location": "Ajouter un entrepôt",
  "add unit": "Ajouter une unité",
  "add where money can be sent": "Ajouter une destination d'envoi",
  "add your first product": "Ajoutez votre premier produit",
  "admin": "Administrateur",
  "ads by jb": "Publicités JB",
  "affiliate": "Affilié",
  "aggregate outflow": "Total des dépenses",
  "alert": "Alerte",
  "all": "Tout",
  "all items are stocked above target safety levels": "Tous les articles sont au-dessus du seuil de sécurité",
  "all systems running normally": "Tous les systèmes fonctionnent normalement",
  "allowance": "Indemnité",
  "allowances": "Indemnités",
  "analytics": "Analyses",
  "audit ledger": "Registre des rapports",
  "authorized measurement units (uom)": "Unités de mesure autorisées",
  "auto if empty": "Automatique si vide",
  "auto-created from your company name.": "Créé automatiquement à partir du nom de votre entreprise.",
  "auto-generated-key": "Clé générée automatiquement",
  "awaiting layout selection and customer assignment": "En attente du choix de mise en page et du client",
  "barcode controls & stock": "Code-barres et stock",
  "barcode label layout option": "Option de mise en page de l'étiquette",
  "base unit": "Unité de base",
  "best sellers": "Meilleures ventes",
  "billing & delivery address": "Adresse de facturation et de livraison",
  "branch yield": "Revenus de la succursale",
  "brand directories": "Répertoires de marques",
  "bulk template": "Modèle groupé",
  "bulk upload": "Import groupé",
  "business address": "Adresse de l'entreprise",
  "business email": "E-mail de l'entreprise",
  "business industry niche": "Type d'activité",
  "business industry niche / type": "Type d'activité",
  "business intelligence": "Rapports d'activité",
  "business phone": "Téléphone de l'entreprise",
  "business profile": "Profil de l'entreprise",
  "business settings": "Paramètres de l'entreprise",
  "business setup": "Configuration de l'entreprise",
  "buying": "Achat",
  "call local agent": "Appeler l'agent local",
  "canvas processing": "Traitement de l'image",
  "cartons per master box": "Cartons par boîte principale",
  "cash & bank": "Caisse et banque",
  "cash bank matrix": "Tableau caisse-banque",
  "cash-bank-matrix screen": "Écran caisse-banque",
  "cashier override": "Dérogation caissier",
  "categories": "Catégories",
  "category directories": "Répertoires de catégories",
  "central vaults & bank accounts": "Coffres et comptes bancaires",
  "channel rules & costs": "Règles et coûts des canaux",
  "choose package": "Choisir un forfait",
  "choose payment mode for detailed date-based metrics": "Choisissez le mode de paiement pour les détails par date",
  "choose the product type, starting level, and how many units each level contains.": "Choisissez le type de produit, le niveau de départ et le nombre d'unités par niveau.",
  "city / office location": "Ville",
  "click to remove payment channel": "Cliquez pour retirer ce canal de paiement",
  "cloud network connected": "Connecté au cloud",
  "cloud synchronized ledger node": "Registre synchronisé avec le cloud",
  "code & link": "Code et lien",
  "collapse sidebar": "Réduire le menu latéral",
  "collect due balance installment": "Encaisser un acompte sur le solde dû",
  "commercial profit & loss account": "Compte de résultat",
  "commit ledger": "Enregistrer la dépense",
  "communicating with payment server": "Communication avec le serveur de paiement",
  "company / business name": "Nom de l'entreprise",
  "company address": "Adresse de l'entreprise",
  "company code": "Code de l'entreprise",
  "company legal name": "Raison sociale",
  "company level settings": "Paramètres de l'entreprise",
  "company tin (taxpayer identification number)": "Numéro d'identification fiscale",
  "company vat registration number": "Numéro de TVA de l'entreprise",
  "compile report": "Créer le rapport",
  "configure core business metadata, localized compliance tin/vat numbers, legal currency markers, and system color mode preferences.": "Configurez les données de l'entreprise, les numéros fiscaux, le symbole monétaire et le mode couleur du système.",
  "configure corporate accounts & bank keys in settings": "Configurez les comptes et clés bancaires dans les paramètres",
  "configure new selling price": "Définir un nouveau prix de vente",
  "confirm & initialize payment": "Confirmer et lancer le paiement",
  "conflict overrides action log": "Journal des dérogations de conflit",
  "consolidated margin curve": "Courbe des ventes et bénéfices",
  "contact for deployment": "Contactez-nous pour l'activation",
  "contact helpline / phone no": "Numéro d'assistance",
  "continue": "Continuer",
  "copied": "Copié",
  "copy": "Copier",
  "corporate headquarters address": "Adresse du siège social",
  "cost of goods sold": "Coût des marchandises",
  "cost of purchase": "Coût d'achat",
  "create": "Créer",
  "custom interval": "Choisir les dates",
  "custom roles & permissions": "Rôles et permissions personnalisés",
  "customer identity (required for store credit)": "Identité du client (requise pour le crédit)",
  "customer totals and credit": "Totaux et crédit du client",
  "customers screen": "Écran des clients",
  "daily": "Quotidien",
  "daily sales volume timeline": "Évolution du volume des ventes quotidiennes",
  "dashboard ad code published.": "Code publicitaire du tableau de bord publié.",
  "dashboard ad deleted and turned off.": "Publicité du tableau de bord supprimée et désactivée.",
  "dashboard ad placement": "Emplacement publicitaire du tableau de bord",
  "dashboard ads": "Publicités du tableau de bord",
  "date aggregated timeline transactions": "Transactions regroupées par date",
  "days remaining": "Jours restants",
  "de-register store storage bin": "Désenregistrer l'emplacement de stockage",
  "default portion qty": "Quantité par défaut",
  "deferred credit": "Paiement différé",
  "define packet, dose and tab selling": "Définir la vente par paquet, dose et comprimé",
  "delete item": "Supprimer l'article",
  "delete role": "Supprimer le rôle",
  "deliveries screen": "Écran des livraisons",
  "delivery menu": "Menu livraison",
  "delivery payment methods": "Modes de paiement livraison",
  "delivery rider": "Livreur",
  "department": "Département",
  "descriptor & visual assets": "Description et visuels",
  "device is offline": "Appareil hors ligne",
  "device is online": "Appareil en ligne",
  "direct phone line": "Ligne directe",
  "disabled": "Désactivé",
  "discard": "Annuler",
  "dose / middle price": "Prix de la dose",
  "download csv": "Télécharger CSV",
  "download pdf": "Télécharger PDF",
  "download spreadsheet template": "Télécharger le modèle de tableau",
  "download template": "Télécharger le modèle",
  "dual channel": "Détail et gros",
  "dues owed": "Créances",
  "edit item": "Modifier l'article",
  "edit login": "Modifier les identifiants",
  "edit role": "Modifier le rôle",
  "email address": "Adresse e-mail",
  "enabled": "Activé",
  "english": "Anglais",
  "enter brand name": "Saisir le nom de la marque",
  "enter business brand name": "Saisir le nom de marque de l'entreprise",
  "enter category": "Saisir la catégorie",
  "enter company legal registry name": "Saisir la raison sociale",
  "enter company legal registry name...": "Saisir la raison sociale...",
  "enter product name": "Saisir le nom du produit",
  "enter supervisor override code": "Saisir le code de dérogation du superviseur",
  "expenses management": "Gestion des dépenses",
  "expenses screen": "Écran des dépenses",
  "export csv": "Exporter CSV",
  "export pdf": "Exporter PDF",
  "fast movers": "Produits à rotation rapide",
  "fifo, average, and batch price control.": "Contrôle des prix FIFO, moyen et par lot.",
  "filter by customer, phone, or ticket ref": "Filtrer par client, téléphone ou référence",
  "filter invoice ledger list by customized date intervals": "Filtrer les factures par périodes personnalisées",
  "filter report": "Filtrer le rapport",
  "fits images & separates background instantly": "Ajuste les images et détoure le fond instantanément",
  "flyer": "Dépliant",
  "forecasting": "Prévisions",
  "forecasting screen": "Écran des prévisions",
  "generated based on company name for subdomain routing": "Généré à partir du nom de l'entreprise pour le sous-domaine",
  "generated company username/key": "Nom d'utilisateur ou clé généré pour l'entreprise",
  "gross income": "Revenu total",
  "gross revenue": "Chiffre d'affaires",
  "hali ya mauzo na manunuzi": "État des ventes et des achats",
  "helpline displayed on layouts": "Numéro d'assistance affiché sur les documents",
  "image": "Image",
  "import": "Importer",
  "inspect client receipt details": "Consulter les détails du reçu client",
  "intelligence & auditing": "Rapports d'activité",
  "inventory sales distribution": "Répartition des ventes de stock",
  "inventory screen": "Écran de l'inventaire",
  "invoice & branding customization": "Personnalisation de la facture et de la marque",
  "invoice footer tagline / memo": "Mention en bas de facture",
  "items sold": "Articles vendus",
  "label directories": "Répertoires d'étiquettes",
  "last sync": "Dernière synchronisation",
  "last30Days": "30 derniers jours",
  "last7Days": "7 derniers jours",
  "leave blank to auto-create sku": "Laisser vide pour générer le code produit",
  "ledger actions": "Actions du registre",
  "ledger analytics": "Analyses du registre",
  "legal payment currency symbol": "Symbole de la monnaie officielle",
  "legal street, plot no, city, country": "Rue, numéro de parcelle, ville, pays",
  "liquidity & consolidated cash flow": "Liquidités et flux de trésorerie",
  "live manager override station": "Poste de dérogation du responsable",
  "loading...": "Chargement...",
  "local mode (offline)": "Mode local (hors ligne)",
  "locked": "Verrouillé",
  "low stock alert level": "Seuil d'alerte de stock",
  "low stock alerts": "Alertes de stock faible",
  "lowest unit": "Plus petite unité",
  "lucy ai": "Lucy IA",
  "lucy assistant": "Assistante Lucy",
  "manage": "Gérer",
  "manage active subscriptions and premium account plans easily to expand store limits.": "Gérez facilement vos abonnements et forfaits premium pour étendre les limites du magasin.",
  "manager": "Responsable",
  "margin gain per unit": "Marge par unité",
  "materials": "Matériel",
  "meetings": "Réunions",
  "min wholesale qty": "Quantité min. en gros",
  "month": "Mois",
  "monthly": "Mensuel",
  "multi-channel split breakdown": "Répartition multi-canal",
  "my jasper suite": "Mon Jasper",
  "net gross profit": "Bénéfice",
  "net outcome in selected range": "Résultat net sur la période",
  "new buying cost (per unit)": "Nouveau coût d'achat (par unité)",
  "new category": "Nouvelle catégorie",
  "new commercial sales document wizard": "Assistant de création de document de vente",
  "new product": "Nouveau produit",
  "new unit": "Nouvelle unité",
  "no changes to selling price": "Aucun changement de prix de vente",
  "no delivery payment methods. pos default will be applied": "Aucun mode de paiement livraison. Le mode par défaut sera utilisé",
  "no image": "Aucune image",
  "no logistics delivery transactions logged yet": "Aucune livraison enregistrée",
  "no operating expenses recorded within selected range": "Aucune dépense enregistrée sur la période",
  "no products yet": "Aucun produit pour l'instant",
  "no sales transactions found in selected period": "Aucune vente sur la période sélectionnée",
  "no tenant suite available": "Aucun espace de travail disponible",
  "no transactions matched research parameters": "Aucune transaction ne correspond à la recherche",
  "non-pharmaceutical": "Non pharmaceutique",
  "none": "Aucun",
  "notifications & auto reports": "Notifications et rapports automatiques",
  "off": "Désactivé",
  "on": "Activé",
  "onboarding": "Inscription",
  "online now": "En ligne",
  "open": "Ouvrir",
  "open workspace menu": "Ouvrir le menu de l'espace de travail",
  "operating expenses burden": "Charges d'exploitation",
  "operating expenses logs receipt": "Reçu du journal des dépenses",
  "operational integrity intact": "Intégrité opérationnelle confirmée",
  "order": "Commande",
  "orders": "Commandes",
  "orders / tx": "Commandes et transactions",
  "organic subscribers": "Abonnés organiques",
  "outbound stock pulling logic": "Logique de sortie de stock",
  "outstanding sales invoices marked as credit tabs": "Factures de vente à crédit impayées",
  "overall report": "Rapport général",
  "overview": "Vue d'ensemble",
  "overview screen": "Écran de vue d'ensemble",
  "owner full name": "Nom complet du propriétaire",
  "owner pin password": "Mot de passe",
  "package": "Forfait",
  "package name": "Nom du forfait",
  "packages": "Forfaits",
  "packet, dose, half dose and tab pricing": "Tarification paquet, dose, demi-dose et comprimé",
  "partner": "Partenaire",
  "past 1 year": "Année écoulée",
  "past 3 months": "3 derniers mois",
  "past 7 days": "7 derniers jours",
  "past30Days": "30 derniers jours",
  "payment methods": "Modes de paiement",
  "payouts": "Versements",
  "pending sync": "Synchronisation en attente",
  "permanent": "Permanent",
  "permissions": "Permissions",
  "pharmaceutical": "Pharmaceutique",
  "pharmacist": "Pharmacien",
  "pharmacy": "Pharmacie",
  "pharmacy unit hierarchy": "Hiérarchie des unités pharmaceutiques",
  "phone number": "Numéro de téléphone",
  "phone number (optional)": "Numéro de téléphone (facultatif)",
  "phone with country code": "Téléphone avec indicatif pays",
  "png signature (500x500 pix)": "Signature PNG (500×500 px)",
  "point of sale (pos)": "Point de vente",
  "pos screen": "Écran du point de vente",
  "preferences": "Préférences",
  "preview": "Aperçu",
  "print report": "Imprimer le rapport",
  "print standard a4 pdf document": "Imprimer un document PDF A4",
  "procurement": "Achats",
  "product brand": "Marque du produit",
  "product catalogue": "Catalogue des produits",
  "product image": "Image du produit",
  "product markup": "Marge du produit",
  "product name / title": "Nom du produit",
  "product profitability": "Rentabilité du produit",
  "product search & picker tool": "Outil de recherche et sélection de produits",
  "product type": "Type de produit",
  "products below security thresholds": "Produits sous le seuil de sécurité",
  "products management": "Gestion des produits",
  "products screen": "Écran des produits",
  "profile photo (500x500 pix)": "Photo de profil (500×500 px)",
  "profile settings": "Paramètres du profil",
  "profit": "Bénéfice",
  "profit & cogs reports": "Rapports de bénéfice et coût des marchandises",
  "profit margin": "Marge bénéficiaire",
  "promotional materials": "Supports promotionnels",
  "provide audited verification slip": "Fournir le justificatif vérifié",
  "purchase trend": "Tendance des achats",
  "purchases list": "Liste des achats",
  "purchases management": "Gestion des achats",
  "quantity added": "Quantité ajoutée",
  "quick actions": "Actions rapides",
  "quick sale": "Vente rapide",
  "quick sale portions": "Portions de vente rapide",
  "quotations & proforma invoices": "Devis et factures proforma",
  "read": "Lecture",
  "ready for direct printing or local downloads": "Prêt pour l'impression directe ou le téléchargement",
  "real-time audit log with operational action menus": "Journal d'audit en temps réel avec menus d'actions",
  "received payments & channel ledger": "Paiements reçus et registre des canaux",
  "recent sales": "Ventes récentes",
  "region of operations": "Pays ou région",
  "register new product": "Enregistrer un nouveau produit",
  "register new staff profile": "Enregistrer un nouveau profil employé",
  "register staff": "Enregistrer un employé",
  "registered": "Enregistré",
  "registered categories": "Catégories enregistrées",
  "registered staff": "Employés enregistrés",
  "registered staff accounts": "Comptes employés enregistrés",
  "registered units": "Unités enregistrées",
  "registered warehouses & store stock locations": "Entrepôts et emplacements de stock enregistrés",
  "remaining customer dockets debt pending settlement": "Dettes clients restant à régler",
  "removes image background.": "Supprime le fond de l'image.",
  "replenish stock": "Réapprovisionner le stock",
  "reporting terminal": "Rapports",
  "reports screen": "Écran des rapports",
  "retail & wholesale": "Détail et gros",
  "retail package selling": "Vente au détail par paquet",
  "retail price": "Prix de détail",
  "retail scan barcode (acts as sku item code)": "Code-barres détail (sert de code produit)",
  "retry": "Réessayer",
  "role": "Rôle",
  "role name": "Nom du rôle",
  "roles": "Rôles",
  "salary": "Salaire",
  "salary type": "Type de salaire",
  "sales & expenses reports": "Rapports de ventes et dépenses",
  "sales & purchase status": "État des ventes et des achats",
  "sales forecasting": "Prévisions des ventes",
  "sales list": "Liste des ventes",
  "sales trend": "Tendance des ventes",
  "sales velocity": "Vitesse des ventes",
  "save / edit ad code": "Enregistrer ou modifier le code publicitaire",
  "save / edit bottom ad": "Enregistrer ou modifier la publicité inférieure",
  "save ad code": "Enregistrer le code publicitaire",
  "save bottom ad": "Enregistrer la publicité inférieure",
  "save changes": "Enregistrer les modifications",
  "save login": "Enregistrer les identifiants",
  "save registration": "Enregistrer l'inscription",
  "save settings": "Enregistrer les paramètres",
  "saved": "Enregistré",
  "saving": "Enregistrement",
  "saving...": "Enregistrement...",
  "scan barcode / qr ean code with reader": "Scannez le code-barres ou le QR avec le lecteur",
  "search and select items to print barcodes for": "Recherchez et sélectionnez les produits pour imprimer les codes-barres",
  "search code, barcode or title": "Rechercher par code, code-barres ou nom",
  "search customer, staff code, item": "Rechercher un client, un code employé ou un article",
  "search products...": "Rechercher des produits...",
  "search receipt id, client customer name": "Rechercher par numéro de reçu ou nom du client",
  "search transactions": "Rechercher des transactions",
  "search workspace": "Rechercher dans l'espace de travail",
  "search workspace...": "Rechercher dans l'espace de travail...",
  "select active payment rail": "Sélectionner le canal de paiement actif",
  "select an audited branch segment to inspect": "Sélectionnez une succursale à examiner",
  "select and add catalog items above": "Sélectionnez et ajoutez des articles du catalogue ci-dessus",
  "select category": "Sélectionner une catégorie",
  "select core source account": "Sélectionner le compte source",
  "select language": "Choisir la langue",
  "select language / badili lugha": "Choisir la langue",
  "select language / velg pris / badili lugha": "Choisir la langue",
  "select target wallet or bank": "Sélectionner le portefeuille ou la banque cible",
  "selected payment mode details": "Détails du mode de paiement sélectionné",
  "sell / count unit": "Unité de vente ou de comptage",
  "sell mode": "Mode de vente",
  "sell retail": "Vente au détail",
  "sell wholesale": "Vente en gros",
  "seller": "Vendeur",
  "set as transfer source & open panel": "Définir comme source de transfert et ouvrir le panneau",
  "set low-stock alert.": "Définir l'alerte de stock faible.",
  "settings access": "Accès aux paramètres",
  "settings screen": "Écran des paramètres",
  "settle outstanding payment-in": "Régler le paiement en attente",
  "shop": "Boutique",
  "show product pictures in pos": "Afficher les images des produits au point de vente",
  "shows name & barcode text (no price)": "Affiche le nom et le code-barres, sans prix",
  "shows name, price & barcode": "Affiche le nom, le prix et le code-barres",
  "shows only the scan barcode bars": "Affiche uniquement les barres du code-barres",
  "sign out failed, please try again": "Échec de la déconnexion, veuillez réessayer",
  "simulated push dispatched": "Notification test envoyée",
  "slow movers": "Produits à rotation lente",
  "smart batch costing": "Calcul intelligent des coûts par lot",
  "smart pos & business management": "Point de vente intelligent et gestion d'entreprise",
  "staff & hr": "Personnel et RH",
  "staff control center": "Centre de gestion du personnel",
  "staff member": "Employé",
  "staff members": "Employés",
  "staff onboarding": "Intégration du personnel",
  "staff payroll, sessions and performance": "Paie, sessions et performance du personnel",
  "staff type": "Type d'employé",
  "standard staff": "Employé standard",
  "starting level": "Niveau de départ",
  "statement line items": "Détails du rapport",
  "sticky bottom ad banner": "Bannière publicitaire fixe en bas",
  "sticky bottom ad deleted and turned off.": "Bannière fixe supprimée et désactivée.",
  "sticky bottom ad published.": "Bannière fixe publiée.",
  "stock alerts": "Alertes de stock",
  "stock controller": "Responsable du stock",
  "stock replenishment": "Réapprovisionnement",
  "stock replenishment & prices": "Réapprovisionnement et prix",
  "stock valuations & warehouse split": "Valorisation du stock et répartition par entrepôt",
  "store": "Magasin",
  "store location": "Emplacement de stockage",
  "store locations": "Emplacements de stockage",
  "strips per box": "Plaquettes par boîte",
  "sub affiliate subscribers": "Abonnés des sous-affiliés",
  "sub affiliates": "Sous-affiliés",
  "submit payment-in reference": "Envoyer la référence du paiement",
  "subscribe": "S'abonner",
  "subscription": "Abonnement",
  "sum outcome inside date range": "Résultat total sur la période",
  "supervisor": "Superviseur",
  "supplier": "Fournisseur",
  "suppliers management": "Gestion des fournisseurs",
  "suppliers screen": "Écran des fournisseurs",
  "supported formats: jpg, png, webp. maximum file size: 2mb": "Formats acceptés : JPG, PNG, WEBP. Taille max. : 2 Mo",
  "swahili": "Swahili",
  "switch to dark mode": "Passer en mode sombre",
  "switch to day mode": "Passer en mode jour",
  "switch to light mode": "Passer en mode clair",
  "sync now": "Synchroniser maintenant",
  "system & branch configurations": "Configurations du système et des succursales",
  "system module / functionality": "Module ou fonctionnalité du système",
  "system settings": "Paramètres du système",
  "system subscription options": "Options d'abonnement du système",
  "tagline": "Slogan",
  "talk to lucy": "Parler à Lucy",
  "tasks": "Tâches",
  "tax identification number (tin)": "Numéro d'identification fiscale",
  "temporary": "Temporaire",
  "temporary staff": "Employé temporaire",
  "tenant": "Locataire",
  "tenants": "Locataires",
  "today's sale": "Ventes du jour",
  "today's sales": "Ventes du jour",
  "todays sales": "Ventes du jour",
  "top products": "Meilleurs produits",
  "total allowances": "Total des indemnités",
  "total payment in (inflows)": "Total des encaissements",
  "total payment out (outflows)": "Total des décaissements",
  "total payment-ins collected": "Total des encaissements collectés",
  "total payroll": "Masse salariale totale",
  "total spending": "Total des dépenses",
  "total staff": "Total du personnel",
  "total staff cost": "Coût total du personnel",
  "tracked skus": "Produits suivis",
  "trial expired": "Période d'essai expirée",
  "type product name or barcode to add": "Saisissez le nom du produit ou le code-barres",
  "unified branch accounts & reports": "Comptes et rapports unifiés des succursales",
  "unified stock registry desk": "Registre unifié du stock",
  "units": "Unités",
  "units moved": "Articles vendus",
  "update customer details or items": "Mettre à jour les informations du client ou les articles",
  "update settings": "Mettre à jour les paramètres",
  "upload product image": "Téléverser l'image du produit",
  "upload spreadsheet": "Téléverser un tableur",
  "used to sign in & receive otp resets": "Utilisé pour la connexion et la réinitialisation par code",
  "username": "Nom d'utilisateur",
  "vat number": "Numéro de TVA",
  "vat-yyyyyy-y (if applicable)": "TVA-AAAAAA-A (le cas échéant)",
  "verification email address": "Adresse e-mail de vérification",
  "video": "Vidéo",
  "view details": "Voir les détails",
  "view or print thermal slip": "Voir ou imprimer le ticket thermique",
  "view product": "Voir le produit",
  "void / clear entire basket": "Vider tout le panier",
  "void transaction indices permanently": "Annuler définitivement les transactions",
  "waiter": "Serveur",
  "week": "Semaine",
  "weekly": "Hebdomadaire",
  "whatsapp / mobile number": "WhatsApp ou numéro de mobile",
  "whole package sale value": "Valeur de vente du paquet entier",
  "why are you moving this money": "Pourquoi transférez-vous cet argent",
  "write": "Écriture",
  "year": "Année",
  "your whatsapp / mobile number": "Votre WhatsApp ou numéro de mobile",
};

/* ------------------------------------------------------------------ */

if (!existsSync(FILE)) {
  console.error(`Faili haipatikani: ${FILE}`);
  console.error('Endesha script hii kutoka mzizi wa mradi.');
  process.exit(1);
}

let src = readFileSync(FILE, 'utf8');
const backup = `${FILE}.bak2`;
copyFileSync(FILE, backup);

function existingKeys(text, lang) {
  const marker = new RegExp(`\\n(\\s*)${lang}\\s*:\\s*\\{`);
  const m = marker.exec(text);
  if (!m) return null;
  const open = text.indexOf('{', m.index);
  let depth = 0;
  for (let i = open; i < text.length; i++) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}') {
      depth--;
      if (depth === 0) {
        const block = text.slice(open, i);
        return {
          keys: new Set([...block.matchAll(/"([^"]+)"\s*:\s*"/g)].map((x) => x[1])),
          insertAt: m.index + m[0].length,
          indent: m[1] + '  ',
        };
      }
    }
  }
  return null;
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const summary = [];

// Kuanzia mwisho kwenda mwanzo ili nafasi za kuingiza zisibadilike
for (const [lang, dict] of [['fr', FR], ['ar', AR]]) {
  const info = existingKeys(src, lang);
  if (!info) {
    summary.push(`${lang.toUpperCase()}: sehemu haikupatikana, imerukwa`);
    continue;
  }
  const toAdd = Object.entries(dict).filter(([k]) => !info.keys.has(k));
  if (!toAdd.length) {
    summary.push(`${lang.toUpperCase()}: zote zilikuwepo, hakuna iliyoongezwa`);
    continue;
  }
  const lines = toAdd
    .map(([k, v]) => `${info.indent}"${esc(k)}": "${esc(v)}",`)
    .join('\n');
  src = src.slice(0, info.insertAt) + '\n' + lines + src.slice(info.insertAt);
  summary.push(
    `${lang.toUpperCase()}: zimeongezwa ${toAdd.length}, zimerukwa ${Object.keys(dict).length - toAdd.length}`,
  );
}

writeFileSync(FILE, src, 'utf8');

console.log(`Backup: ${backup}\n`);
summary.forEach((s) => console.log('  ' + s));
console.log('\nSasa endesha:  node scripts/i18n-gap.mjs');
