begin;

-- Preserve a complete, queryable before-image for every row changed below.
-- This makes the one-time financial cleanup recoverable without deleting any
-- referral, commission, affiliate, partner, or tenant record.
create table if not exists public.migration_row_backups (
  id bigint generated by default as identity primary key,
  migration_version text not null,
  table_name text not null,
  record_id text not null,
  row_data jsonb not null,
  backed_up_at timestamptz not null default now(),
  unique (migration_version, table_name, record_id)
);

alter table public.migration_row_backups enable row level security;
alter table public.migration_row_backups force row level security;
revoke all on table public.migration_row_backups from public, anon, authenticated;

-- A package list price is not cash received. Clear financial fields from
-- referrals whose payment has not reached an explicitly settled state.
insert into public.migration_row_backups (
  migration_version, table_name, record_id, row_data
)
select
  '20260721000100', 'referred_customers', referral.id::text, to_jsonb(referral)
from public.referred_customers referral
where lower(trim(coalesce(referral.payment_status, ''))) not in (
  'paid', 'payment paid', 'success', 'successful', 'completed',
  'payment completed', 'approved', 'verified', 'settled'
)
and (coalesce(referral.amount_paid, 0) <> 0 or coalesce(referral.commission_amount, 0) <> 0)
on conflict (migration_version, table_name, record_id) do nothing;

update public.referred_customers
set
  amount_paid = 0,
  commission_amount = 0
where lower(trim(coalesce(payment_status, ''))) not in (
  'paid', 'payment paid', 'success', 'successful', 'completed',
  'payment completed', 'approved', 'verified', 'settled'
)
and (coalesce(amount_paid, 0) <> 0 or coalesce(commission_amount, 0) <> 0);

-- Pending audit rows may preserve attribution, but must never carry revenue,
-- commission or payout values before the associated payment is settled.
insert into public.migration_row_backups (
  migration_version, table_name, record_id, row_data
)
select
  '20260721000100', 'commission_ledger', ledger.id::text, to_jsonb(ledger)
from public.commission_ledger ledger
where lower(trim(coalesce(ledger.status, ''))) not in (
  'paid', 'payment paid', 'success', 'successful', 'completed',
  'payment completed', 'approved', 'verified', 'settled'
)
and (
  coalesce(ledger.revenue_amount, 0) <> 0
  or coalesce(ledger.network_pool_20, 0) <> 0
  or coalesce(ledger.manager_commission_5, 0) <> 0
  or coalesce(ledger.sub_affiliate_gross_commission_15, 0) <> 0
  or coalesce(ledger.withholding_tax_amount, 0) <> 0
  or coalesce(ledger.sub_affiliate_net_payout, 0) <> 0
)
on conflict (migration_version, table_name, record_id) do nothing;

update public.commission_ledger
set
  revenue_amount = 0,
  network_pool_20 = 0,
  manager_commission_5 = 0,
  sub_affiliate_gross_commission_15 = 0,
  withholding_tax_amount = 0,
  sub_affiliate_net_payout = 0
where lower(trim(coalesce(status, ''))) not in (
  'paid', 'payment paid', 'success', 'successful', 'completed',
  'payment completed', 'approved', 'verified', 'settled'
)
and (
  coalesce(revenue_amount, 0) <> 0
  or coalesce(network_pool_20, 0) <> 0
  or coalesce(manager_commission_5, 0) <> 0
  or coalesce(sub_affiliate_gross_commission_15, 0) <> 0
  or coalesce(withholding_tax_amount, 0) <> 0
  or coalesce(sub_affiliate_net_payout, 0) <> 0
);

-- Remove stale running totals only for affiliate accounts that have no
-- settled referral or ledger entry at all. Customer/referral counts remain.
insert into public.migration_row_backups (
  migration_version, table_name, record_id, row_data
)
select
  '20260721000100', 'affiliates', affiliate.id::text, to_jsonb(affiliate)
from public.affiliates affiliate
where not exists (
  select 1 from public.referred_customers referral
  where coalesce(referral.sub_affiliate_id, referral.affiliate_id)::text = affiliate.id::text
    and lower(trim(coalesce(referral.payment_status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1 from public.commission_ledger ledger
  where coalesce(ledger.sub_affiliate_id, ledger.affiliate_id)::text = affiliate.id::text
    and lower(trim(coalesce(ledger.status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1 from public.affiliate_commissions commission
  where commission.affiliate_id::text = affiliate.id::text
    and lower(trim(coalesce(commission.status, ''))) in (
      'available', 'paid', 'success', 'successful', 'completed',
      'approved', 'verified', 'settled'
    )
)
and (
  coalesce(affiliate.total_revenue, 0) <> 0
  or coalesce(affiliate.gross_commission, 0) <> 0
  or coalesce(affiliate.withholding_tax, 0) <> 0
  or coalesce(affiliate.net_payout, 0) <> 0
  or coalesce(affiliate.paid_amount, 0) <> 0
  or coalesce(affiliate.pending_payout, 0) <> 0
)
on conflict (migration_version, table_name, record_id) do nothing;

update public.affiliates affiliate
set
  total_revenue = 0,
  gross_commission = 0,
  withholding_tax = 0,
  net_payout = 0,
  paid_amount = 0,
  pending_payout = 0
where not exists (
  select 1
  from public.referred_customers referral
  where coalesce(referral.sub_affiliate_id, referral.affiliate_id)::text = affiliate.id::text
    and lower(trim(coalesce(referral.payment_status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1
  from public.commission_ledger ledger
  where coalesce(ledger.sub_affiliate_id, ledger.affiliate_id)::text = affiliate.id::text
    and lower(trim(coalesce(ledger.status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1
  from public.affiliate_commissions commission
  where commission.affiliate_id::text = affiliate.id::text
    and lower(trim(coalesce(commission.status, ''))) in (
      'available', 'paid', 'success', 'successful', 'completed',
      'approved', 'verified', 'settled'
    )
);

insert into public.migration_row_backups (
  migration_version, table_name, record_id, row_data
)
select
  '20260721000100', 'affiliate_partners', partner.id::text, to_jsonb(partner)
from public.affiliate_partners partner
where not exists (
  select 1 from public.referred_customers referral
  where referral.parent_super_agent_id::text = partner.id::text
    and lower(trim(coalesce(referral.payment_status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1 from public.commission_ledger ledger
  where ledger.parent_super_agent_id::text = partner.id::text
    and lower(trim(coalesce(ledger.status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1 from public.affiliate_commissions commission
  where commission.agent_id::text = partner.user_id::text
    and lower(trim(coalesce(commission.status, ''))) in (
      'available', 'paid', 'success', 'successful', 'completed',
      'approved', 'verified', 'settled'
    )
)
and (
  coalesce(partner.total_revenue, 0) <> 0
  or coalesce(partner.manager_commission, 0) <> 0
  or coalesce(partner.withholding_tax, 0) <> 0
  or coalesce(partner.net_payout, 0) <> 0
)
on conflict (migration_version, table_name, record_id) do nothing;

update public.affiliate_partners partner
set
  total_revenue = 0,
  manager_commission = 0,
  withholding_tax = 0,
  net_payout = 0
where not exists (
  select 1
  from public.referred_customers referral
  where referral.parent_super_agent_id::text = partner.id::text
    and lower(trim(coalesce(referral.payment_status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1
  from public.commission_ledger ledger
  where ledger.parent_super_agent_id::text = partner.id::text
    and lower(trim(coalesce(ledger.status, ''))) in (
      'paid', 'payment paid', 'success', 'successful', 'completed',
      'payment completed', 'approved', 'verified', 'settled'
    )
)
and not exists (
  select 1
  from public.affiliate_commissions commission
  where commission.agent_id::text = partner.user_id::text
    and lower(trim(coalesce(commission.status, ''))) in (
      'available', 'paid', 'success', 'successful', 'completed',
      'approved', 'verified', 'settled'
    )
);

commit;
