-- Reversible quarantine archive used before demo-account cleanup. The archive
-- is backend-only and stores exact row JSON; it does not delete source rows.

begin;

create table if not exists private.demo_cleanup_batches (
  id uuid primary key default gen_random_uuid(),
  reason text not null,
  manifest jsonb not null,
  status text not null default 'prepared'
    check (status in ('prepared', 'quarantined', 'purged', 'restored')),
  prepared_at timestamptz not null default now(),
  quarantined_at timestamptz,
  purged_at timestamptz,
  restored_at timestamptz
);

create table if not exists private.demo_cleanup_archive (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references private.demo_cleanup_batches(id) on delete restrict,
  source_schema text not null,
  source_table text not null,
  record_key text not null,
  row_data jsonb not null,
  archived_at timestamptz not null default now(),
  unique (batch_id, source_schema, source_table, record_key)
);

create index if not exists demo_cleanup_archive_batch_table_idx
  on private.demo_cleanup_archive (batch_id, source_schema, source_table);

revoke all on table private.demo_cleanup_batches
  from public, anon, authenticated, service_role;
revoke all on table private.demo_cleanup_archive
  from public, anon, authenticated, service_role;
grant select, insert, update on table private.demo_cleanup_batches to service_role;
grant select, insert on table private.demo_cleanup_archive to service_role;

commit;
